AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a ECS service on AWS Fargate, using image build and stored in AWS ECR Container.
Parameters:
  RepositoryName:
    Type: String
    Description: A name for the ECR Repository
  ClusterName:
    Type: String
    Description: Name for the ECS cluster
  ServiceName:
    Type: String
    Description: Name for the ECS service
  TaskName:
    Type: String
    Description: Name of the Task defined in Task Definition schema "family" key
  SecurityGroup:
    Type: String
    Default: sg-0ad3f5bf6d56e8151
    Description: Security Group to be used

Resources:
  MyECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
  MyECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterName
      ClusterSettings:
        - Name: containerInsights # Enable Container Insight Logs
          Value: enabled

# During 1st new Deployment to Cloudformation, disable this part. After complete Task definition creation,
# enable this part and rerun this Cloudformation build to update the stack and create a new Service in the Cluster
  MyClusterService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref MyECSCluster
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskName
      DesiredCount: 1
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
            - subnet-0b597d7e7dbd03718
            - subnet-0b5916be75b287744
            - subnet-0f260ae6a79311725

Outputs:
  ECRRepository:
    Value: !Ref MyECRRepository
  ECSCluster:
    Value: !Ref MyECSCluster
  ClusterService:
    Value: !Ref MyClusterService