AWSTemplateFormatVersion: '2010-09-09'
Description: IaC to deploy ECS Cluster and Service on AWS Fargate to run application from ECR image.
Parameters:
  ClusterName:
    Type: String
    Description: Name for the ECS cluster
  ServiceName:
    Type: String
    Description: Name for the ECS service
  TaskName:
    Type: String
    Description: Name of the Task defined in Task Definition schema family
  SecurityGroup:
    Type: String
    Default: sg-0ad3f5bf6d56e8151
    Description: Security Group to be used

Resources:
  MyECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterName
      ClusterSettings:
        - Name: containerInsights # Enable Container Insight Logs
          Value: enabled

  MyClusterService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref MyECSCluster
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskName
      DesiredCount: 1
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
            - subnet-0b597d7e7dbd03718
            - subnet-0b5916be75b287744
            - subnet-0f260ae6a79311725
Outputs:
  ECSCluster:
    Value: !Ref MyECSCluster
  ClusterService:
    Value: !Ref MyClusterService