AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a ECS service on AWS Fargate, using image build and stored in AWS ECR Container.
Parameters:
  ECRRepo:
    Type: String
    Description: Name of the ECR Repo
  ClusterName:
    Type: String
    Default: my-gi-NextJS-app-poc-cluster-develop
    Description: A name for the cluster
  ContainerName:
    Type: String
    Default: my-gi-NextJS-app-develop
    Description: A name for the Container
  ServiceName:
    Type: String
    Default: my-gi-NextJS-app-service-develop
    Description: A name for the service
  ContainerPort:
    Type: Number
    Default: 3000
    Description: What port number the application inside the docker container is binding to
  Version:
    Type: String
    Description: Version number following the app/package.json version number
  MySecurityGroup:
    Type: String
    Default: sg-0ad3f5bf6d56e8151
    Description: Security Group to be used

Resources:
  MyECSDevelopCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterName
      ClusterSettings:
        - Name: containerInsights # Enable Container Insight Logs
          Value: enabled
  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Ref ServiceName
      RequiresCompatibilities:
        - 'FARGATE'
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: 'awsvpc'
      ExecutionRoleArn: arn:aws:iam::128115030554:role/ecsTaskExecutionRole
      # TaskRoleArn: <your_task_role_arn>

      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Join ['', [!Ref 'ECRRepo', ':', !Ref 'Version']]
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Essential: true

  MyClusterService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref MyECSCluster
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 2
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Ref MySecurityGroup
          Subnets:
            - subnet-0b597d7e7dbd03718
            - subnet-0b5916be75b287744
            - subnet-0f260ae6a79311725
Outputs:
  ECSCluster:
    Value: !Ref MyECSDevelopCluster
  ClusterService:
    Value: !Ref MyClusterService