name: 'Deploy to Prod AWS CloudFormation'

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Cloudformation Build
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    environment: production

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # Setup SAM CLI  
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # sam deploy
      - run: sam package --template-file ./ecsCloudformation_prod.yaml --s3-bucket my-gi-ecs-poc-bucket --output-template-file ecsCloudformation_prod-deploy.yaml && aws cloudformation deploy --template-file ecsCloudformation_prod-deploy.yaml --stack-name ecs-poc-cf-deploy-stack-prod --capabilities CAPABILITY_NAMED_IAM --debug